<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/

class AchievementSummary_List_View extends Vtiger_KList_View {

    function preProcess(Vtiger_Request $request, $display = true)
    {
        $viewer = $this->getViewer($request);
        $recordModel=Vtiger_Record_Model::getCleanInstance('AchievementSummary');
        $closingDate=Vtiger_Record_Model::getInstanceById(2434264,'ClosingDate');
        $date=$closingDate->get("date");
        $viewer->assign('date',$date);//业绩每月截止日期
        $viewer->assign('RECORD',$recordModel);
        parent::preProcess($request, $display);//TODO: Change the autogenerated stub
    }

    function process(Vtiger_Request $request)
    {
        $strPublic = $request->get('public');
        if($strPublic=='exportCsv'){
            global $adb;
            $subQuerySQL='';
            $subQuerySQLEnd='';
            $renewsubQuerySQLEnd='';
            $achievementallotStatistic='vtiger_achievementsummary.realarriveachievement';
            $sql_order = " ORDER BY vtiger_achievementsummary.achievementmonth DESC,vtiger_achievementsummary.createtime DESC";
            if($request->get('achievementids')){
                $subQuerySQL .= " and vtiger_achievementsummary.achievementid in (".implode(',',$request->get('achievementids')).') ';
                $effectiverefundSQL='';
            }else{
                $department = getDepartmentinfo($request->get('department'));
                $start_achievemonth = $request->get('datatime');
                $end_achievemonth = $request->get('enddatatime');
                if($start_achievemonth<$end_achievemonth){
                    $useractivemonthnew="vtiger_useractivemonthnew.activedate>='".$start_achievemonth."' AND vtiger_useractivemonthnew.activedate<='".$end_achievemonth."'";
                    $achAchievementmonth="a.achievementmonth >='".$start_achievemonth."' AND a.achievementmonth<='".$end_achievemonth."'";
                }elseif($start_achievemonth>$end_achievemonth){
                    $useractivemonthnew="vtiger_useractivemonthnew.activedate>='".$end_achievemonth."' AND vtiger_useractivemonthnew.activedate<='".$start_achievemonth."'";
                    $achAchievementmonth="a.achievementmonth <='".$start_achievemonth."' AND a.achievementmonth>='".$end_achievemonth."'";
                }else{
                    $useractivemonthnew="vtiger_useractivemonthnew.activedate='".$start_achievemonth."'";
                    $achAchievementmonth="a.achievementmonth ='".$start_achievemonth."'";
                }
                $achievementallotStatistic="if(vtiger_achievementsummary.achievementtype='renew',vtiger_achievementsummary.realarriveachievement,(SELECT sum(vtiger_achievementallot_statistic.arriveachievement) FROM vtiger_achievementallot_statistic WHERE vtiger_achievementallot_statistic.achievementmonth >='".$start_achievemonth."' and vtiger_achievementallot_statistic.achievementmonth<='".$end_achievemonth."' AND vtiger_achievementallot_statistic.receivedpaymentownid IN(SELECT subordinateid FROM vtiger_useractivemonthnew LEFT JOIN vtiger_usergraderoyalty ON vtiger_usergraderoyalty.userid=vtiger_useractivemonthnew.userid WHERE ((vtiger_useractivemonthnew.userid=vtiger_achievementsummary.userid AND vtiger_usergraderoyalty.staffrank=1) OR (vtiger_useractivemonthnew.userid=vtiger_achievementsummary.userid  AND vtiger_useractivemonthnew.userid=vtiger_useractivemonthnew.subordinateid AND vtiger_usergraderoyalty.staffrank=0))
                    AND ".$useractivemonthnew.") AND (vtiger_achievementallot_statistic.achievementtype='newadd' or (vtiger_achievementallot_statistic.achievementtype='renew' AND vtiger_achievementallot_statistic.more_years_renew=1))))";
                $subQuerySQL .= " and vtiger_achievementsummary.departmentid in ('".implode("','",$department)."')";
                $subQuerySQLEnd=" and vtiger_achievementsummary.achievementmonth >='".$start_achievemonth."' and vtiger_achievementsummary.achievementmonth<='".$end_achievemonth."' ";
                $effectiverefundSQL="(SELECT sum(if(a.effectiverefund>0,a.effectiverefund,0)) AS effectiverefund FROM 
                    `vtiger_achievementallot_statistic` AS a WHERE a.receivedpaymentownid IN(SELECT subordinateid FROM vtiger_useractivemonthnew LEFT JOIN vtiger_usergraderoyalty ON vtiger_usergraderoyalty.userid=vtiger_useractivemonthnew.userid WHERE ((vtiger_useractivemonthnew.userid=vtiger_achievementsummary.userid AND vtiger_usergraderoyalty.staffrank=1) OR (vtiger_useractivemonthnew.userid=vtiger_achievementsummary.userid  AND vtiger_useractivemonthnew.userid=vtiger_useractivemonthnew.subordinateid AND vtiger_usergraderoyalty.staffrank=0))
                    AND ".$useractivemonthnew.") AND ".$achAchievementmonth." 
                    AND a.achievementtype='newadd' 
                    AND isleave=0)";
                $renewsubQuerySQLEnd=$subQuerySQL;
            }

            if($request->get('confirmstatus')){
                $subQuerySQL .= ' and confirmstatus="'.$request->get('confirmstatus').'"';
            }
            if($request->get('achievementtype')!='renew'){
                $subQuerySQL .= " and achievementtype='newadd'";
            }else{
                $subQuerySQL .= " and achievementtype='renew'";
            }
            $subQuerySQL .=" AND vtiger_achievementsummary.performancetype!='mpersontype'";
            $sql = "SELECT ( vtiger_departments.departmentname ) AS departmentid,
                    vtiger_achievementsummary.departmentid AS departmentid_reference,
                    vtiger_achievementsummary.unit_price,
                    vtiger_achievementsummary.arriveachievement,
                    vtiger_achievementsummary.realarriveachievement,
                    vtiger_achievementsummary.effectiverefund as effectiverefund2,
                    ".$effectiverefundSQL." as effectiverefund,
                    ".$achievementallotStatistic." as allrealarriveachievement,
                    vtiger_achievementsummary.invoicecompany,
                    (SELECT	last_name FROM vtiger_users WHERE vtiger_achievementsummary.userid = vtiger_users.id) AS userid,vtiger_achievementsummary.createtime,
                    vtiger_achievementsummary.achievementmonth,
                    vtiger_achievementsummary.confirmstatus,
                    vtiger_achievementsummary.employeelevel,
                    vtiger_achievementsummary.achievementtype,
                    (SELECT usercode FROM vtiger_users WHERE vtiger_users.id=vtiger_achievementsummary.userid limit 1) AS usercode,
                    (SELECT employeenumber FROM vtiger_users WHERE vtiger_users.id=vtiger_achievementsummary.userid limit 1) AS employeenumber,
                    (select sum(IFNULL(achtemp.actualroyalty,0)) from  vtiger_achievementsummary achtemp where achtemp.userid=vtiger_achievementsummary.userid and achtemp.achievementmonth=vtiger_achievementsummary.achievementmonth and achtemp.performancetype in('departmenttype','persontype')) as actualroyalty,
                    vtiger_achievementsummary.achievementid 
                FROM
                    vtiger_achievementsummary
                    LEFT JOIN vtiger_departments ON vtiger_departments.departmentid = vtiger_achievementsummary.departmentid 
                WHERE
                    1 = 1  
                 ".$subQuerySQL.$subQuerySQLEnd;
            $notReNewData="SELECT vtiger_achievementsummary.userid FROM
                    vtiger_achievementsummary
                    LEFT JOIN vtiger_departments ON vtiger_departments.departmentid = vtiger_achievementsummary.departmentid 
                WHERE
                    1 = 1".$subQuerySQL.$subQuerySQLEnd;
            $sql.=" UNION SELECT ( vtiger_departments.departmentname ) AS departmentid,
                    vtiger_achievementsummary.departmentid AS departmentid_reference,
                    0 as unit_price,
                    vtiger_achievementsummary.arriveachievement,
                    vtiger_achievementsummary.realarriveachievement,
                    0 as effectiverefund2,
                    0 as effectiverefund,
                    vtiger_achievementsummary.realarriveachievement as allrealarriveachievement,
                    vtiger_achievementsummary.invoicecompany,
                    (SELECT	last_name FROM vtiger_users WHERE vtiger_achievementsummary.userid = vtiger_users.id) AS userid,vtiger_achievementsummary.createtime,
                    vtiger_achievementsummary.achievementmonth,
                    vtiger_achievementsummary.confirmstatus,
                    vtiger_achievementsummary.employeelevel,
                    vtiger_achievementsummary.achievementtype,
                    (SELECT usercode FROM vtiger_users WHERE vtiger_users.id=vtiger_achievementsummary.userid limit 1) AS usercode,
                    (SELECT employeenumber FROM vtiger_users WHERE vtiger_users.id=vtiger_achievementsummary.userid limit 1) AS employeenumber,
                    (select sum(IFNULL(achtemp.actualroyalty,0)) from  vtiger_achievementsummary achtemp where achtemp.userid=vtiger_achievementsummary.userid and achtemp.achievementmonth=vtiger_achievementsummary.achievementmonth and achtemp.performancetype in('departmenttype','persontype')) as actualroyalty,
                    vtiger_achievementsummary.achievementid 
                FROM
                    vtiger_achievementsummary
                    LEFT JOIN vtiger_departments ON vtiger_departments.departmentid = vtiger_achievementsummary.departmentid 
                WHERE
                    1 = 1 ".$renewsubQuerySQLEnd.$subQuerySQLEnd." AND achievementtype='renew' AND vtiger_achievementsummary.actualroyalty>0 AND vtiger_achievementsummary.userid not in(".$notReNewData.")";


            $result = $adb->run_query_allrecords($sql);
            ob_clean();                              //清空缓存

            global $root_directory;

            $array= array();
            $array[]=iconv('utf-8','GB18030//IGNORE','区域');
            $array[]=iconv('utf-8','GB18030//IGNORE','部门');
            $array[]=iconv('utf-8','GB18030//IGNORE','姓名');
            $array[]=iconv('utf-8','GB18030//IGNORE','收款');
            $array[]=iconv('utf-8','GB18030//IGNORE','到账业绩');
            $array[]=iconv('utf-8','GB18030//IGNORE','到账业绩(新单+多年单续费)');
            $array[]=iconv('utf-8','GB18030//IGNORE','有效回款');
            $array[]=iconv('utf-8','GB18030//IGNORE','业绩月份');
            $array[]=iconv('utf-8','GB18030//IGNORE','新单/续费');
            $array[]=iconv('utf-8','GB18030//IGNORE','是否完结');
            $array[]=iconv('utf-8','GB18030//IGNORE','工号');
            $array[]=iconv('utf-8','GB18030//IGNORE','职工编号');
            $array[]=iconv('utf-8','GB18030//IGNORE','职位');
            $array[]=iconv('utf-8','GB18030//IGNORE','提成（新单+续费）');

            $fileName ="销售业绩汇总表_" . time();  //这里定义表名。简单点的就直接  $fileName = time();

            header('Content-Type: application/vnd.ms-excel');   //header设置
            header("Content-Disposition: attachment;filename=".$fileName.".csv");
            header('Cache-Control: max-age=0');
            $fp = fopen('php://output','a');    //打开php文件句柄，php://output表示直接输出到PHP缓存,a表示将输出的内容追加到文件末尾
            fputcsv($fp,$array);  //fputcsv() 函数将行格式$head化为 CSV 并写入一个打开的文件$fp。
            if(!empty($result)){
                foreach($result as $key=>$value){
                    $array=array();
                    $array[]=iconv('utf-8','GB18030//IGNORE', $value['invoicecompany']);
                    $array[]=iconv('utf-8','GB18030//IGNORE',$value['departmentid']);
                    $array[]=iconv('utf-8','GB18030//IGNORE',$value['userid']);
                    $array[]=iconv('utf-8','GB18030//IGNORE',$value['unit_price']);
                    $array[]=iconv('utf-8','GB18030//IGNORE',$value['realarriveachievement']);
                    $array[]=iconv('utf-8','GB18030//IGNORE',$value['allrealarriveachievement']);
                    $array[]=iconv('utf-8','GB18030//IGNORE',$value['effectiverefund']);
                    $array[]=iconv('utf-8','GB18030//IGNORE',$value['achievementmonth']);
                    $array[]=iconv('utf-8','GB18030//IGNORE',vtranslate($value['achievementtype'],'AchievementSummary'));
                    $array[]=iconv('utf-8','GB18030//IGNORE',vtranslate($value['confirmstatus'],'AchievementSummary'));
                    $array[]=iconv('utf-8','GB18030//IGNORE',str_pad($value['usercode'],6,0,STR_PAD_LEFT)."\t");
                    $array[]=iconv('utf-8','GB18030//IGNORE',"\t".$value['employeenumber']);
                    $array[]=iconv('utf-8','GB18030//IGNORE',$value['employeelevel']);
                    $array[]=iconv('utf-8','GB18030//IGNORE',$value['actualroyalty']);
                    fputcsv($fp,$array);
                }
            }
            fclose($fp);
            exit;
            /*
            include_once $root_directory.'libraries/PHPExcel/PHPExcel.php';

            $phpexecl=new PHPExcel();

            // Set document properties
            $phpexecl->getProperties()->setCreator("nie junwei")
                ->setLastModifiedBy("nie junwei")
                ->setTitle("Office 2007 XLSX achievementsummary Document")
                ->setSubject("Office 2007 XLSX achievementsummary Document")
                ->setDescription("Test document for Office 2007 XLSX, generated using classes.")
                ->setKeywords("office 2007 openxml php")
                ->setCategory("achievementsummary");


            // 添加头信处
            $phpexecl->setActiveSheetIndex(0)
                ->setCellValue('A1', '区域')
                ->setCellValue('B1', '部门')
                ->setCellValue('C1', '姓名')
                ->setCellValue('D1', '收款')
                ->setCellValue('E1', '到账业绩')
                ->setCellValue('F1', '到账业绩(新单+多年单续费)')
                ->setCellValue('G1', '有效回款')
                ->setCellValue('H1', '业绩月份')
                ->setCellValue('I1', '新单/续费')
                ->setCellValue('J1', '是否完结')
                ->setCellValue('K1', '工号')
                ->setCellValue('L1', '提成（新单+续费')
            ;
            //设置自动居中
            $phpexecl->getActiveSheet()->getStyle('A1:K1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
            //$result=array(1,2,3,4,5,6,7,3,8,9,10);

            //设置边框
            $phpexecl->getActiveSheet()->getStyle('A1:K1')->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
            if(!empty($result)){
                foreach($result as $key=>$value){
                    $current=$key+2;
                    //$purchasemount=$value['purchasemount']+$value['waici']+$value['qite']+$value['meijai']+ $value['xalong']+$value['costing'];
                    $phpexecl->setActiveSheetIndex(0)
                        ->setCellValueExplicit('A'.$current, $value['invoicecompany'])
                        ->setCellValueExplicit('B'.$current, $value['departmentid'])
                        ->setCellValueExplicit('C'.$current, $value['userid'])
                        ->setCellValueExplicit('D'.$current, $value['unit_price'])
                        ->setCellValueExplicit('E'.$current, $value['realarriveachievement'])
                        ->setCellValueExplicit('F'.$current, $value['allrealarriveachievement'])

                        ->setCellValueExplicit('G'.$current, $value['effectiverefund'])
                        ->setCellValueExplicit('H'.$current, $value['achievementmonth'])
                        ->setCellValueExplicit('I'.$current, vtranslate($value['achievementtype'],'AchievementSummary'))
                        ->setCellValueExplicit('J'.$current, vtranslate($value['confirmstatus'],'AchievementSummary'))
                        ->setCellValueExplicit('K'.$current, $value['usercode'])
                    ;
                    //加上边框
                    $phpexecl->getActiveSheet()->getStyle('A'.$current.':K'.$current)->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
                }
            }

            // 设置工作表的名移
            $phpexecl->getActiveSheet()->setTitle('销售业绩汇总表');

            // Set active sheet index to the first sheet, so Excel opens this as the first sheet
            $phpexecl->setActiveSheetIndex(0);

            header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            header('Content-Disposition: attachment;filename="销售业绩汇总表.csv"');
            header('Cache-Control: max-age=0');

            header('Cache-Control: max-age=1');


            header ('Expires: Mon, 14 Jul 2015 08:18:00 GMT'); // Date in the past
            header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
            header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
            header ('Pragma: public'); // HTTP/1.0

            $objWriter = PHPExcel_IOFactory::createWriter($phpexecl, 'Excel2007');
            $objWriter->save('php://output');*/
            exit;
        } elseif($strPublic=='selectPage') {
            $moduleName = $request->getModule();
            $viewer = $this->getViewer($request);
            $viewer->assign('DEPARTMENT',getDepartment());
            $moduleModel = Vtiger_Module_Model::getInstance($moduleName);
            $confirmstatus = $moduleModel::getConfirmStatus();
            $viewer->assign('CONFIRMSTATUS',$confirmstatus);
            $getAchievementType = $moduleModel::getAchievementType();
            $viewer->assign('ACHIEVEMENTTYPE',$getAchievementType);
            $viewer->view('selectPage.tpl', $moduleName);
            exit;

        } elseif($strPublic=='exportFinanceCsv') {
            global $site_URL, $current_user;
            header('location:'.$site_URL.'temp/achievementsummary'.$current_user->id.'.xlsx');
        }elseif($strPublic=='baiduv'){
            global $adb;
            $moduleName = $request->getModule();
            $viewer = $this->getViewer($request);
            $viewer->assign('DEPARTMENT',getDepartment());
            $sql="SELECT vtiger_baiduvsetting.*,vtiger_departments.departmentname as department2 FROM vtiger_baiduvsetting LEFT JOIN vtiger_departments ON vtiger_baiduvsetting.department = vtiger_departments.departmentid";
            $baiduvSettingList=$adb->run_query_allrecords($sql);
            $viewer->assign('BAIDUVSETTINGLIST',$baiduvSettingList);
            $viewer->view('BaiduvSetting.tpl', $moduleName);
            exit;
        }elseif($strPublic=='baiduvwages'){
            global $adb;
            $moduleName = $request->getModule();
            $viewer = $this->getViewer($request);

            $recordModel = Vtiger_Record_Model::getCleanInstance('AchievementSummary');
            $viewer->assign('USER',$recordModel->getUserIDName());

            $sql = 'select bds.baiduvstaffwagesid,bds.setmonth,bds.staffwages,d.departmentname,u.last_name from vtiger_baiduvstaffwages as bds left join vtiger_users as u on u.id=bds.userid left join vtiger_user2department as utd on utd.userid=u.id left join vtiger_departments as d on d.departmentid=utd.departmentid';

            $baiduvSettingList=$adb->run_query_allrecords($sql);
            $viewer->assign('BAIDUVWAGESLIST',$baiduvSettingList);
            $viewer->view('BaiduvWages.tpl', $moduleName);
            exit;
        }

        $viewer = $this->getViewer($request);
        $recordModel=Vtiger_Record_Model::getCleanInstance('AchievementSummary');
        $viewer->assign('RECORD',$recordModel);
        parent::process($request);

    }

}