<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
//ini_set('display_errors','on'); error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
class ContractDelaySign_List_View extends Vtiger_KList_View {
    function preProcess(Vtiger_Request $request, $display = true)
    {
        $viewer = $this->getViewer($request);
        $report = $request->get("report");
        $viewer->assign('VIEW', $request->get('view'));
        $recordModel=ContractDelaySign_Record_Model::getCleanInstance("ContractDelaySign");
        $viewer->assign('ISNOTYUN',0);
        if($report=='notyun'){
            $viewer->assign('CONTINUECOLUMN',$recordModel->noTyunContinueColumn);
            $viewer->assign('ISNOTYUN',1);
        }else{
            $viewer->assign('CONTINUECOLUMN',$recordModel->tyunContinueColumn);
        }
        parent::preProcess($request, $display); // TODO: Change the autogenerated stub
    }
    function process(Vtiger_Request $request)
    {
        //parent::process($request);
        $viewer = $this->getViewer($request);
        $moduleName = $request->getModule();
        $moduleModel = Vtiger_Module_Model::getInstance($moduleName);//module相关的数据
        $this->viewName = $request->get('viewname');
        $viewer->assign('VIEWNAME', $this->viewName);

        if ($request->isAjax()) {
            $this->initializeListViewContents($request, $viewer);//竟然调用两次，这边其实是ajax调用的，哈哈！！
            $viewer->assign('CURRENT_USER_MODEL', Users_Record_Model::getCurrentUserModel());
        }

        global $configcontracttypeNameTYUN;
        $viewer->assign('VIEW', $request->get('view'));
        $viewer->assign('MODULE_MODEL', $moduleModel);
        $viewer->assign('TYUNTYPE', $configcontracttypeNameTYUN);
        $recordModel=ContractDelaySign_Record_Model::getCleanInstance("ContractDelaySign");
        $report=$request->get("report");
        $viewer->assign('ISNOTYUN',0);
        if($report=='notyun'){
            $viewer->assign('CONTINUECOLUMN',$recordModel->noTyunContinueColumn);
            $viewer->assign('ISNOTYUN',1);
        }else{
            $viewer->assign('CONTINUECOLUMN',$recordModel->tyunContinueColumn);
        }
        global $current_user ;
//        print_r($request->get('view'));exit;
        $viewer->view('ListViewContents.tpl', $moduleName);
    }
}
