<?php

$workflows=array (
  0 => '1076',
  'workflowsid' => '1076',
  1 => '产品执行流程',
  'workflowsname' => '产品执行流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SalesorderProductsrel',
  'mountmodule' => 'SalesorderProductsrel',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '1077',
      'workflowstagesid' => '1077',
      1 => '产品项目生成',
      'workflowstagesname' => '产品项目生成',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '1076',
      'workflowsid' => '1076',
      9 => '4',
      'timelimit' => '4',
      10 => 'ChiefCheck',
      'handleaction' => 'ChiefCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '1078',
      'workflowstagesid' => '1078',
      1 => '执行完成',
      'workflowstagesname' => '执行完成',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '1076',
      'workflowsid' => '1076',
      9 => '4',
      'timelimit' => '4',
      10 => 'ChiefCheck',
      'handleaction' => 'ChiefCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>