<?php

$workflows=array (
  0 => '124',
  'workflowsid' => '124',
  1 => '业务流',
  'workflowsname' => '业务流',
  2 => '1',
  'iscontract' => '1',
  3 => '1',
  'iscontent' => '1',
  4 => '1',
  'isattachment' => '1',
  5 => '1',
  'ischargeback' => '1',
  6 => 'SalesOrder',
  'mountmodule' => 'SalesOrder',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '125',
      'workflowstagesid' => '125',
      1 => '第一个节点',
      'workflowstagesname' => '第一个节点',
      2 => '1',
      'isproductmanger' => '1',
      3 => 'H10',
      'isrole' => 'H10',
      4 => '1',
      'iscost' => '1',
      5 => '1',
      'sequence' => '1',
      6 => '不提醒',
      'manalert' => '不提醒',
      7 => '审核提醒',
      'auditalert' => '审核提醒',
      8 => '124',
      'workflowsid' => '124',
      9 => NULL,
      'timelimit' => NULL,
      10 => NULL,
      'handleaction' => NULL,
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '200',
      'workflowstagesid' => '200',
      1 => '第二个节点',
      'workflowstagesname' => '第二个节点',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H10',
      'isrole' => 'H10',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => 'nowarn',
      'manalert' => 'nowarn',
      7 => 'nowarn',
      'auditalert' => 'nowarn',
      8 => '124',
      'workflowsid' => '124',
      9 => NULL,
      'timelimit' => NULL,
      10 => NULL,
      'handleaction' => NULL,
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '201',
      'workflowstagesid' => '201',
      1 => '第三个节点',
      'workflowstagesname' => '第三个节点',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H10',
      'isrole' => 'H10',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => '',
      'manalert' => '',
      7 => '',
      'auditalert' => '',
      8 => '124',
      'workflowsid' => '124',
      9 => NULL,
      'timelimit' => NULL,
      10 => NULL,
      'handleaction' => NULL,
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    4 => 
    array (
      0 => '202',
      'workflowstagesid' => '202',
      1 => '第四个节点',
      'workflowstagesname' => '第四个节点',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => '',
      'manalert' => '',
      7 => '',
      'auditalert' => '',
      8 => '124',
      'workflowsid' => '124',
      9 => NULL,
      'timelimit' => NULL,
      10 => NULL,
      'handleaction' => NULL,
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>