<?php

$workflows=array (
  0 => '128',
  'workflowsid' => '128',
  1 => '无合同类工单',
  'workflowsname' => '无合同类工单',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SalesOrder',
  'mountmodule' => 'SalesOrder',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '138',
      'workflowstagesid' => '138',
      1 => '执行部门审核',
      'workflowstagesname' => '执行部门审核',
      2 => '1',
      'isproductmanger' => '1',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => '不提醒',
      'manalert' => '不提醒',
      7 => '审核提醒',
      'auditalert' => '审核提醒',
      8 => '128',
      'workflowsid' => '128',
      9 => NULL,
      'timelimit' => NULL,
      10 => NULL,
      'handleaction' => NULL,
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '197',
      'workflowstagesid' => '197',
      1 => '财务首付款审核',
      'workflowstagesname' => '财务首付款审核',
      2 => '1',
      'isproductmanger' => '1',
      3 => 'H10',
      'isrole' => 'H10',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => '',
      'manalert' => '',
      7 => '不提醒',
      'auditalert' => '不提醒',
      8 => '128',
      'workflowsid' => '128',
      9 => NULL,
      'timelimit' => NULL,
      10 => NULL,
      'handleaction' => NULL,
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '198',
      'workflowstagesid' => '198',
      1 => '执行部门操作',
      'workflowstagesname' => '执行部门操作',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => '',
      'manalert' => '',
      7 => '不提醒',
      'auditalert' => '不提醒',
      8 => '128',
      'workflowsid' => '128',
      9 => NULL,
      'timelimit' => NULL,
      10 => NULL,
      'handleaction' => NULL,
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    4 => 
    array (
      0 => '199',
      'workflowstagesid' => '199',
      1 => '财务尾款审核',
      'workflowstagesname' => '财务尾款审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => '不提醒',
      'manalert' => '不提醒',
      7 => '',
      'auditalert' => '',
      8 => '128',
      'workflowsid' => '128',
      9 => NULL,
      'timelimit' => NULL,
      10 => NULL,
      'handleaction' => NULL,
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>