<?php

$workflows=array (
  0 => '1305',
  'workflowsid' => '1305',
  1 => '标准合同申请流程',
  'workflowsname' => '标准合同申请流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'ServiceContracts',
  'mountmodule' => 'ServiceContracts',
  'stage' => 
  array (
    1 => 
    array (
      0 => '1306',
      'workflowstagesid' => '1306',
      1 => '合同打印',
      'workflowstagesname' => '合同打印',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H90',
      'isrole' => 'H90',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => '1',
      'manalert' => '1',
      7 => NULL,
      'auditalert' => NULL,
      8 => '1305',
      'workflowsid' => '1305',
      9 => '8',
      'timelimit' => '8',
      10 => 'ChiefCheck',
      'handleaction' => 'ChiefCheck',
      11 => '635',
      'subworkflowsid' => '635',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      'nostd' => 
      array (
        1 => 
        array (
          0 => '1079',
          'workflowstagesid' => '1079',
          1 => '产品负责人写成本',
          'workflowstagesname' => '产品负责人写成本',
          2 => '0',
          'isproductmanger' => '0',
          3 => '',
          'isrole' => '',
          4 => '0',
          'iscost' => '0',
          5 => '1',
          'sequence' => '1',
          6 => '0',
          'manalert' => '0',
          7 => NULL,
          'auditalert' => NULL,
          8 => '635',
          'workflowsid' => '635',
          9 => '4',
          'timelimit' => '4',
          10 => 'ChiefCheck',
          'handleaction' => 'ChiefCheck',
          11 => '0',
          'subworkflowsid' => '0',
          12 => NULL,
          'iseditdata' => NULL,
          13 => NULL,
          'modulestatus' => NULL,
          14 => NULL,
          'isnextnode' => NULL,
          15 => NULL,
          'workflowstagesflag' => NULL,
        ),
      ),
    ),
    2 => 
    array (
      0 => '1389',
      'workflowstagesid' => '1389',
      1 => '合同领取',
      'workflowstagesname' => '合同领取',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H90',
      'isrole' => 'H90',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '1305',
      'workflowsid' => '1305',
      9 => '8',
      'timelimit' => '8',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '1390',
      'workflowstagesid' => '1390',
      1 => '合同签收',
      'workflowstagesname' => '合同签收',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H90',
      'isrole' => 'H90',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '1305',
      'workflowsid' => '1305',
      9 => '8',
      'timelimit' => '8',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>