<?php

$workflows=array (
  0 => '1658',
  'workflowsid' => '1658',
  1 => '工作流测试1',
  'workflowsname' => '工作流测试1',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SalesOrder',
  'mountmodule' => 'SalesOrder',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    23 => 
    array (
      0 => '1659',
      'workflowstagesid' => '1659',
      1 => '工作流阶段',
      'workflowstagesname' => '工作流阶段',
      2 => '1',
      'isproductmanger' => '1',
      3 => 'H40',
      'isrole' => 'H40',
      4 => '0',
      'iscost' => '0',
      5 => '23',
      'sequence' => '23',
      6 => '1',
      'manalert' => '1',
      7 => NULL,
      'auditalert' => NULL,
      8 => '1658',
      'workflowsid' => '1658',
      9 => '100',
      'timelimit' => '100',
      10 => 'ChiefCheck',
      'handleaction' => 'ChiefCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>