<?php

$workflows=array (
  0 => '1670',
  'workflowsid' => '1670',
  1 => '其他部门',
  'workflowsname' => '其他部门',
  2 => '1',
  'iscontract' => '1',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SalesOrder',
  'mountmodule' => 'SalesOrder',
  'stage' => 
  array (
    1 => 
    array (
      0 => '1671',
      'workflowstagesid' => '1671',
      1 => '请问恶趣味额',
      'workflowstagesname' => '请问恶趣味额',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H27',
      'isrole' => 'H27',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '1670',
      'workflowsid' => '1670',
      9 => '7',
      'timelimit' => '7',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>