<?php

$workflows=array (
  0 => '1866',
  'workflowsid' => '1866',
  1 => '外出会议学习出差审批流',
  'workflowsname' => '外出会议学习出差审批流',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'VisitingOrder',
  'mountmodule' => 'VisitingOrder',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '1867',
      'workflowstagesid' => '1867',
      1 => '总监审批',
      'workflowstagesname' => '总监审批',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H81',
      'isrole' => 'H81',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '1866',
      'workflowsid' => '1866',
      9 => '8',
      'timelimit' => '8',
      10 => 'UpCheck',
      'handleaction' => 'UpCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>