<?php

$workflows=array (
  0 => '2131276',
  'workflowsid' => '2131276',
  1 => '充值申请单供应商退款审核流程',
  'workflowsname' => '充值申请单供应商退款审核流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'RefillApplication',
  'mountmodule' => 'RefillApplication',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '2131448',
      'workflowstagesid' => '2131448',
      1 => '部门负责人退款审核',
      'workflowstagesname' => '部门负责人退款审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H78 |##| H79 |##| H94',
      'isrole' => 'H78 |##| H79 |##| H94',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2131276',
      'workflowsid' => '2131276',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'DO_REFUND',
      'workflowstagesflag' => 'DO_REFUND',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '2131451',
      'workflowstagesid' => '2131451',
      1 => '出纳退款审核',
      'workflowstagesname' => '出纳退款审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H107',
      'isrole' => 'H107',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2131276',
      'workflowsid' => '2131276',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => 'DO_REFUND',
      'workflowstagesflag' => 'DO_REFUND',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '2131452',
      'workflowstagesid' => '2131452',
      1 => '申请人确认退款',
      'workflowstagesname' => '申请人确认退款',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2131276',
      'workflowsid' => '2131276',
      9 => '0',
      'timelimit' => '0',
      10 => 'MyCheck',
      'handleaction' => 'MyCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'c_complete',
      'modulestatus' => 'c_complete',
      14 => '0',
      'isnextnode' => '0',
      15 => 'DO_REFUND',
      'workflowstagesflag' => 'DO_REFUND',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>