<?php

$workflows=array (
  0 => '2426996',
  'workflowsid' => '2426996',
  1 => '合同执行',
  'workflowsname' => '合同执行',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'ContractExecution',
  'mountmodule' => 'ContractExecution',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '2427106',
      'workflowstagesid' => '2427106',
      1 => '大模大样',
      'workflowstagesname' => '大模大样',
      2 => '1',
      'isproductmanger' => '1',
      3 => 'H101',
      'isrole' => 'H101',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2426996',
      'workflowsid' => '2426996',
      9 => '1',
      'timelimit' => '1',
      10 => 'REVIEWER',
      'handleaction' => 'REVIEWER',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '1',
      'isnextnode' => '1',
      15 => '1',
      'workflowstagesflag' => '1',
      16 => '143',
      'reviewer' => '143',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>