<?php

$workflows=array (
  0 => '2427186',
  'workflowsid' => '2427186',
  1 => '凯丽隆预开票审核',
  'workflowsname' => '凯丽隆预开票审核',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'Newinvoice',
  'mountmodule' => 'Newinvoice',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '2427187',
      'workflowstagesid' => '2427187',
      1 => '部门一级负责人审核',
      'workflowstagesname' => '部门一级负责人审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2427186',
      'workflowsid' => '2427186',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => 'AUDIT_VERIFICATION',
      'workflowstagesflag' => 'AUDIT_VERIFICATION',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '2427188',
      'workflowstagesid' => '2427188',
      1 => '部门二级负责人审核',
      'workflowstagesname' => '部门二级负责人审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2427186',
      'workflowsid' => '2427186',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'TWO_VERIFICATION',
      'workflowstagesflag' => 'TWO_VERIFICATION',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '2427189',
      'workflowstagesid' => '2427189',
      1 => '发票管理员开立发票',
      'workflowstagesname' => '发票管理员开立发票',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2427186',
      'workflowsid' => '2427186',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'open_invoice',
      'workflowstagesflag' => 'open_invoice',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
    4 => 
    array (
      0 => '2427190',
      'workflowstagesid' => '2427190',
      1 => '发票领取',
      'workflowstagesname' => '发票领取',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2427186',
      'workflowsid' => '2427186',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'receive_invoice',
      'workflowstagesflag' => 'receive_invoice',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>