<?php

$workflows=array (
  0 => '2721631',
  'workflowsid' => '2721631',
  1 => '发票签收--事后签收流程',
  'workflowsname' => '发票签收--事后签收流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'InputInvoice',
  'mountmodule' => 'InputInvoice',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '2721632',
      'workflowstagesid' => '2721632',
      1 => '财务主管审核',
      'workflowstagesname' => '财务主管审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H162',
      'isrole' => 'H162',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721631',
      'workflowsid' => '2721631',
      9 => '0',
      'timelimit' => '0',
      10 => 'maincompany',
      'handleaction' => 'maincompany',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>