<?php

$workflows=array (
  0 => '2721901',
  'workflowsid' => '2721901',
  1 => '客户结算单',
  'workflowsname' => '客户结算单',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'CustomerStatement',
  'mountmodule' => 'CustomerStatement',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '2721902',
      'workflowstagesid' => '2721902',
      1 => '责任会计审核',
      'workflowstagesname' => '责任会计审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H127 |##| H90',
      'isrole' => 'H127 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721901',
      'workflowsid' => '2721901',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '2721903',
      'workflowstagesid' => '2721903',
      1 => '财务主管审核',
      'workflowstagesname' => '财务主管审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721901',
      'workflowsid' => '2721901',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'CWSH',
      'workflowstagesflag' => 'CWSH',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '2721904',
      'workflowstagesid' => '2721904',
      1 => '结算单打印',
      'workflowstagesname' => '结算单打印',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H104 |##| H90',
      'isrole' => 'H104 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721901',
      'workflowsid' => '2721901',
      9 => '0',
      'timelimit' => '0',
      10 => 'maincompany',
      'handleaction' => 'maincompany',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
    4 => 
    array (
      0 => '2721905',
      'workflowstagesid' => '2721905',
      1 => '结算单盖章',
      'workflowstagesname' => '结算单盖章',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H104 |##| H90',
      'isrole' => 'H104 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721901',
      'workflowsid' => '2721901',
      9 => '0',
      'timelimit' => '0',
      10 => 'maincompany',
      'handleaction' => 'maincompany',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>