<?php

$workflows=array (
  0 => '2721639',
  'workflowsid' => '2721639',
  1 => '发票签收--事前签收(非增值税)流程',
  'workflowsname' => '发票签收--事前签收(非增值税)流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'InputInvoice',
  'mountmodule' => 'InputInvoice',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '2721640',
      'workflowstagesid' => '2721640',
      1 => '对应会计签收',
      'workflowstagesname' => '对应会计签收',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721639',
      'workflowsid' => '2721639',
      9 => '0',
      'timelimit' => '0',
      10 => 'maincompany',
      'handleaction' => 'maincompany',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'co',
      'workflowstagesflag' => 'co',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '2721641',
      'workflowstagesid' => '2721641',
      1 => '责任会计签收',
      'workflowstagesname' => '责任会计签收',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721639',
      'workflowsid' => '2721639',
      9 => '0',
      'timelimit' => '0',
      10 => 'maincompany',
      'handleaction' => 'maincompany',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'rs',
      'workflowstagesflag' => 'rs',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>