<?php

$workflows=array (
  0 => '2721630',
  'workflowsid' => '2721630',
  1 => '发票签收--事前签收(增值税)流程',
  'workflowsname' => '发票签收--事前签收(增值税)流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'InputInvoice',
  'mountmodule' => 'InputInvoice',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '2721633',
      'workflowstagesid' => '2721633',
      1 => '对应会计签收',
      'workflowstagesname' => '对应会计签收',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721630',
      'workflowsid' => '2721630',
      9 => '0',
      'timelimit' => '0',
      10 => 'maincompany',
      'handleaction' => 'maincompany',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'co',
      'workflowstagesflag' => 'co',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '2721634',
      'workflowstagesid' => '2721634',
      1 => '责任会计签收发票联',
      'workflowstagesname' => '责任会计签收发票联',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721630',
      'workflowsid' => '2721630',
      9 => '0',
      'timelimit' => '0',
      10 => 'maincompany',
      'handleaction' => 'maincompany',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'rs',
      'workflowstagesflag' => 'rs',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '2721635',
      'workflowstagesid' => '2721635',
      1 => '对应会计录入抵扣联信息',
      'workflowstagesname' => '对应会计录入抵扣联信息',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721630',
      'workflowsid' => '2721630',
      9 => '0',
      'timelimit' => '0',
      10 => 'maincompany',
      'handleaction' => 'maincompany',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'co',
      'workflowstagesflag' => 'co',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
    4 => 
    array (
      0 => '2721636',
      'workflowstagesid' => '2721636',
      1 => '发票管理员签收',
      'workflowstagesname' => '发票管理员签收',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H125',
      'isrole' => 'H125',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721630',
      'workflowsid' => '2721630',
      9 => '0',
      'timelimit' => '0',
      10 => 'maincompany',
      'handleaction' => 'maincompany',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'fp',
      'workflowstagesflag' => 'fp',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
    5 => 
    array (
      0 => '2721637',
      'workflowstagesid' => '2721637',
      1 => '发票管理员认证',
      'workflowstagesname' => '发票管理员认证',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H125',
      'isrole' => 'H125',
      4 => '0',
      'iscost' => '0',
      5 => '5',
      'sequence' => '5',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721630',
      'workflowsid' => '2721630',
      9 => '0',
      'timelimit' => '0',
      10 => 'maincompany',
      'handleaction' => 'maincompany',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'fp',
      'workflowstagesflag' => 'fp',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
    6 => 
    array (
      0 => '2721638',
      'workflowstagesid' => '2721638',
      1 => '发票管理员归档',
      'workflowstagesname' => '发票管理员归档',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H125',
      'isrole' => 'H125',
      4 => '0',
      'iscost' => '0',
      5 => '6',
      'sequence' => '6',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '2721630',
      'workflowsid' => '2721630',
      9 => '0',
      'timelimit' => '0',
      10 => 'maincompany',
      'handleaction' => 'maincompany',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'fp',
      'workflowstagesflag' => 'fp',
      16 => '1',
      'reviewer' => '1',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>