<?php

$workflows=array (
  0 => '3068666',
  'workflowsid' => '3068666',
  1 => '回款核对编辑审核',
  'workflowsname' => '回款核对编辑审核',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'ReceivedPaymentsCollate',
  'mountmodule' => 'ReceivedPaymentsCollate',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '3068667',
      'workflowstagesid' => '3068667',
      1 => '资金主管审核',
      'workflowstagesname' => '资金主管审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '3068666',
      'workflowsid' => '3068666',
      9 => '0',
      'timelimit' => '0',
      10 => 'REVIEWER',
      'handleaction' => 'REVIEWER',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '20',
      'reviewer' => '20',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '3068668',
      'workflowstagesid' => '3068668',
      1 => '财务运营经理审核',
      'workflowstagesname' => '财务运营经理审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '3068666',
      'workflowsid' => '3068666',
      9 => '0',
      'timelimit' => '0',
      10 => 'REVIEWER',
      'handleaction' => 'REVIEWER',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'CAIWUYUNYING',
      'workflowstagesflag' => 'CAIWUYUNYING',
      16 => '43',
      'reviewer' => '43',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>