<?php

$workflows=array (
  0 => '3068715',
  'workflowsid' => '3068715',
  1 => '外贸充值单1',
  'workflowsname' => '外贸充值单1',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'RefillApplication',
  'mountmodule' => 'RefillApplication',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '3068794',
      'workflowstagesid' => '3068794',
      1 => '财务初审',
      'workflowstagesname' => '财务初审',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H78',
      'isrole' => 'H78',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '3068715',
      'workflowsid' => '3068715',
      9 => '0',
      'timelimit' => '0',
      10 => 'REVIEWER',
      'handleaction' => 'REVIEWER',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'AUDIT_FIRST_FOREIGNRECHARGE',
      'workflowstagesflag' => 'AUDIT_FIRST_FOREIGNRECHARGE',
      16 => '43',
      'reviewer' => '43',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '3068795',
      'workflowstagesid' => '3068795',
      1 => '财务复审',
      'workflowstagesname' => '财务复审',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H141 |##| H78',
      'isrole' => 'H141 |##| H78',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '3068715',
      'workflowsid' => '3068715',
      9 => '0',
      'timelimit' => '0',
      10 => 'REVIEWER',
      'handleaction' => 'REVIEWER',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'c_complete',
      'modulestatus' => 'c_complete',
      14 => '0',
      'isnextnode' => '0',
      15 => 'AUDIT_AGAIN_FOREIGNRECHARGE',
      'workflowstagesflag' => 'AUDIT_AGAIN_FOREIGNRECHARGE',
      16 => '43',
      'reviewer' => '43',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>