<?php

$workflows=array (
  0 => '3068814',
  'workflowsid' => '3068814',
  1 => '客户名称变更审核',
  'workflowsname' => '客户名称变更审核',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'AccountNameChangeHistory',
  'mountmodule' => 'AccountNameChangeHistory',
  7 => '2022-01-18 10:54:06',
  'dataupdate' => '2022-01-18 10:54:06',
  'stage' => 
  array (
    1 => 
    array (
      0 => '3068815',
      'workflowstagesid' => '3068815',
      1 => '财务审核',
      'workflowstagesname' => '财务审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '3068814',
      'workflowsid' => '3068814',
      9 => '0',
      'timelimit' => '0',
      10 => 'REVIEWER',
      'handleaction' => 'REVIEWER',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '16',
      'reviewer' => '16',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>