<?php

$workflows=array (
  0 => '366933',
  'workflowsid' => '366933',
  1 => 'Google流程',
  'workflowsname' => 'Google流程',
  2 => '1',
  'iscontract' => '1',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SalesOrder',
  'mountmodule' => 'SalesOrder',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '366935',
      'workflowstagesid' => '366935',
      1 => '项目/产品经理',
      'workflowstagesname' => '项目/产品经理',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H88',
      'isrole' => 'H88',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '366933',
      'workflowsid' => '366933',
      9 => '8',
      'timelimit' => '8',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '1',
      'iseditdata' => '1',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '366936',
      'workflowstagesid' => '366936',
      1 => '财务成本审核',
      'workflowstagesname' => '财务成本审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H121 |##| H127 |##| H90 |##| H171',
      'isrole' => 'H121 |##| H127 |##| H90 |##| H171',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '366933',
      'workflowsid' => '366933',
      9 => '8',
      'timelimit' => '8',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => 'GOOGLE_CONF_TIME',
      'workflowstagesflag' => 'GOOGLE_CONF_TIME',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '2137280',
      'workflowstagesid' => '2137280',
      1 => '提单人关联回款',
      'workflowstagesname' => '提单人关联回款',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '366933',
      'workflowsid' => '366933',
      9 => '0',
      'timelimit' => '0',
      10 => 'MyCheck',
      'handleaction' => 'MyCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'RAYMENT_MATCH',
      'workflowstagesflag' => 'RAYMENT_MATCH',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    4 => 
    array (
      0 => '366938',
      'workflowstagesid' => '366938',
      1 => '项目/产品经理客服分配',
      'workflowstagesname' => '项目/产品经理客服分配',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H88',
      'isrole' => 'H88',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '366933',
      'workflowsid' => '366933',
      9 => '8',
      'timelimit' => '8',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '1',
      'isnextnode' => '1',
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>