<?php

$workflows=array (
  0 => '372',
  'workflowsid' => '372',
  1 => '非标准合同申请流程',
  'workflowsname' => '非标准合同申请流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'ServiceContracts',
  'mountmodule' => 'ServiceContracts',
  'stage' => 
  array (
    1 => 
    array (
      0 => '390',
      'workflowstagesid' => '390',
      1 => '第一级审核',
      'workflowstagesname' => '第一级审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '372',
      'workflowsid' => '372',
      9 => '4',
      'timelimit' => '4',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => '533',
      'subworkflowsid' => '533',
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => 'AUDIT_VERIFICATION',
      'workflowstagesflag' => 'AUDIT_VERIFICATION',
      'nostd' => 
      array (
        1 => 
        array (
          0 => '534',
          'workflowstagesid' => '534',
          1 => '商务总监审核',
          'workflowstagesname' => '商务总监审核',
          2 => '1',
          'isproductmanger' => '1',
          3 => 'H32 |##| H54 |##| H61',
          'isrole' => 'H32 |##| H54 |##| H61',
          4 => '0',
          'iscost' => '0',
          5 => '1',
          'sequence' => '1',
          6 => '0',
          'manalert' => '0',
          7 => NULL,
          'auditalert' => NULL,
          8 => '533',
          'workflowsid' => '533',
          9 => '8',
          'timelimit' => '8',
          10 => 'ChiefCheck',
          'handleaction' => 'ChiefCheck',
          11 => '0',
          'subworkflowsid' => '0',
          12 => NULL,
          'iseditdata' => NULL,
          13 => NULL,
          'modulestatus' => NULL,
          14 => NULL,
          'isnextnode' => NULL,
          15 => NULL,
          'workflowstagesflag' => NULL,
        ),
        2 => 
        array (
          0 => '535',
          'workflowstagesid' => '535',
          1 => '产品负责人审核',
          'workflowstagesname' => '产品负责人审核',
          2 => '1',
          'isproductmanger' => '1',
          3 => 'H25',
          'isrole' => 'H25',
          4 => '0',
          'iscost' => '0',
          5 => '2',
          'sequence' => '2',
          6 => '0',
          'manalert' => '0',
          7 => NULL,
          'auditalert' => NULL,
          8 => '533',
          'workflowsid' => '533',
          9 => '5',
          'timelimit' => '5',
          10 => 'ChiefCheck',
          'handleaction' => 'ChiefCheck',
          11 => '0',
          'subworkflowsid' => '0',
          12 => NULL,
          'iseditdata' => NULL,
          13 => NULL,
          'modulestatus' => NULL,
          14 => NULL,
          'isnextnode' => NULL,
          15 => NULL,
          'workflowstagesflag' => NULL,
        ),
      ),
    ),
    2 => 
    array (
      0 => '391',
      'workflowstagesid' => '391',
      1 => '第二级审核',
      'workflowstagesname' => '第二级审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '372',
      'workflowsid' => '372',
      9 => '4',
      'timelimit' => '4',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'TWO_VERIFICATION',
      'workflowstagesflag' => 'TWO_VERIFICATION',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '392',
      'workflowstagesid' => '392',
      1 => '第三级审核',
      'workflowstagesname' => '第三级审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => NULL,
      'isrole' => NULL,
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '372',
      'workflowsid' => '372',
      9 => '4',
      'timelimit' => '4',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    4 => 
    array (
      0 => '393',
      'workflowstagesid' => '393',
      1 => '财务主管',
      'workflowstagesname' => '财务主管',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H1',
      'isrole' => 'H1',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '372',
      'workflowsid' => '372',
      9 => '4',
      'timelimit' => '4',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'CREATE_CODE',
      'workflowstagesflag' => 'CREATE_CODE',
      'nostd' => 
      array (
      ),
    ),
    5 => 
    array (
      0 => '1391',
      'workflowstagesid' => '1391',
      1 => '合同打印',
      'workflowstagesname' => '合同打印',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H104 |##| H90',
      'isrole' => 'H104 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '5',
      'sequence' => '5',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '372',
      'workflowsid' => '372',
      9 => '8',
      'timelimit' => '8',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'DO_PRINT',
      'workflowstagesflag' => 'DO_PRINT',
      'nostd' => 
      array (
      ),
    ),
    6 => 
    array (
      0 => '798883',
      'workflowstagesid' => '798883',
      1 => '合同盖章',
      'workflowstagesname' => '合同盖章',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H104 |##| H90',
      'isrole' => 'H104 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '6',
      'sequence' => '6',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '372',
      'workflowsid' => '372',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'CLOSE_WORKSTREAM',
      'workflowstagesflag' => 'CLOSE_WORKSTREAM',
      'nostd' => 
      array (
      ),
    ),
    7 => 
    array (
      0 => '798884',
      'workflowstagesid' => '798884',
      1 => '合同领取',
      'workflowstagesname' => '合同领取',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '7',
      'sequence' => '7',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '372',
      'workflowsid' => '372',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    8 => 
    array (
      0 => '798885',
      'workflowstagesid' => '798885',
      1 => '合同收回',
      'workflowstagesname' => '合同收回',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '8',
      'sequence' => '8',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '372',
      'workflowsid' => '372',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>