<?php

$workflows=array (
  0 => '373',
  'workflowsid' => '373',
  1 => '非标准合同业务流程-未开放',
  'workflowsname' => '非标准合同业务流程-未开放',
  2 => '1',
  'iscontract' => '1',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'ServiceContracts',
  'mountmodule' => 'ServiceContracts',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '1397',
      'workflowstagesid' => '1397',
      1 => '产品负责人审核',
      'workflowstagesname' => '产品负责人审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H88',
      'isrole' => 'H88',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '373',
      'workflowsid' => '373',
      9 => '8',
      'timelimit' => '8',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => '1',
      'iseditdata' => '1',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '386',
      'workflowstagesid' => '386',
      1 => '财务首付款审核',
      'workflowstagesname' => '财务首付款审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H90 |##| H171',
      'isrole' => 'H90 |##| H171',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '373',
      'workflowsid' => '373',
      9 => '4',
      'timelimit' => '4',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => '1076',
      'subworkflowsid' => '1076',
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
        1 => 
        array (
          0 => '1077',
          'workflowstagesid' => '1077',
          1 => '产品项目生成',
          'workflowstagesname' => '产品项目生成',
          2 => '0',
          'isproductmanger' => '0',
          3 => '',
          'isrole' => '',
          4 => '0',
          'iscost' => '0',
          5 => '1',
          'sequence' => '1',
          6 => '0',
          'manalert' => '0',
          7 => NULL,
          'auditalert' => NULL,
          8 => '1076',
          'workflowsid' => '1076',
          9 => '4',
          'timelimit' => '4',
          10 => 'ChiefCheck',
          'handleaction' => 'ChiefCheck',
          11 => '0',
          'subworkflowsid' => '0',
          12 => NULL,
          'iseditdata' => NULL,
          13 => NULL,
          'modulestatus' => NULL,
          14 => NULL,
          'isnextnode' => NULL,
          15 => NULL,
          'workflowstagesflag' => NULL,
          16 => '0',
          'reviewer' => '0',
        ),
        2 => 
        array (
          0 => '1078',
          'workflowstagesid' => '1078',
          1 => '执行完成',
          'workflowstagesname' => '执行完成',
          2 => '0',
          'isproductmanger' => '0',
          3 => '',
          'isrole' => '',
          4 => '0',
          'iscost' => '0',
          5 => '2',
          'sequence' => '2',
          6 => '0',
          'manalert' => '0',
          7 => NULL,
          'auditalert' => NULL,
          8 => '1076',
          'workflowsid' => '1076',
          9 => '4',
          'timelimit' => '4',
          10 => 'ChiefCheck',
          'handleaction' => 'ChiefCheck',
          11 => '0',
          'subworkflowsid' => '0',
          12 => NULL,
          'iseditdata' => NULL,
          13 => NULL,
          'modulestatus' => NULL,
          14 => NULL,
          'isnextnode' => NULL,
          15 => NULL,
          'workflowstagesflag' => NULL,
          16 => '0',
          'reviewer' => '0',
        ),
      ),
    ),
    4 => 
    array (
      0 => '1398',
      'workflowstagesid' => '1398',
      1 => '执行部门项目执行',
      'workflowstagesname' => '执行部门项目执行',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H88',
      'isrole' => 'H88',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '373',
      'workflowsid' => '373',
      9 => '0',
      'timelimit' => '0',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => '1',
      'iseditdata' => '1',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    5 => 
    array (
      0 => '388',
      'workflowstagesid' => '388',
      1 => '财务尾款审核',
      'workflowstagesname' => '财务尾款审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H90 |##| H171',
      'isrole' => 'H90 |##| H171',
      4 => '0',
      'iscost' => '0',
      5 => '5',
      'sequence' => '5',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '373',
      'workflowsid' => '373',
      9 => '4',
      'timelimit' => '4',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>