<?php

$workflows=array (
  0 => '379250',
  'workflowsid' => '379250',
  1 => '今日头条开户流程',
  'workflowsname' => '今日头条开户流程',
  2 => '1',
  'iscontract' => '1',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SalesOrder',
  'mountmodule' => 'SalesOrder',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '379251',
      'workflowstagesid' => '379251',
      1 => '项目/产品经理',
      'workflowstagesname' => '项目/产品经理',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H88',
      'isrole' => 'H88',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '379250',
      'workflowsid' => '379250',
      9 => '0',
      'timelimit' => '0',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '1',
      'iseditdata' => '1',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '379253',
      'workflowstagesid' => '379253',
      1 => '财务成本审核',
      'workflowstagesname' => '财务成本审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H90 |##| H171',
      'isrole' => 'H90 |##| H171',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '379250',
      'workflowsid' => '379250',
      9 => '8',
      'timelimit' => '8',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '379255',
      'workflowstagesid' => '379255',
      1 => '财务充值',
      'workflowstagesname' => '财务充值',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102',
      'isrole' => 'H102',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '379250',
      'workflowsid' => '379250',
      9 => '8',
      'timelimit' => '8',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    4 => 
    array (
      0 => '379258',
      'workflowstagesid' => '379258',
      1 => '项目/产品经理客服分配',
      'workflowstagesname' => '项目/产品经理客服分配',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H88',
      'isrole' => 'H88',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '379250',
      'workflowsid' => '379250',
      9 => '8',
      'timelimit' => '8',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '1',
      'isnextnode' => '1',
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>