<?php

$workflows=array (
  0 => '379904',
  'workflowsid' => '379904',
  1 => '无合同无回款发票申请流程',
  'workflowsname' => '无合同无回款发票申请流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'ServiceContracts',
  'mountmodule' => 'ServiceContracts',
  'stage' => 
  array (
    1 => 
    array (
      0 => '379905',
      'workflowstagesid' => '379905',
      1 => '总监审核',
      'workflowstagesname' => '总监审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H79 |##| H83',
      'isrole' => 'H79 |##| H83',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '379904',
      'workflowsid' => '379904',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'a_normal',
      'modulestatus' => 'a_normal',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '379909',
      'workflowstagesid' => '379909',
      1 => '发票打印',
      'workflowstagesname' => '发票打印',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102 |##| H90',
      'isrole' => 'H102 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '379904',
      'workflowsid' => '379904',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '1',
      'iseditdata' => '1',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'edit_financial',
      'workflowstagesflag' => 'edit_financial',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '379910',
      'workflowstagesid' => '379910',
      1 => '提单人现场确认',
      'workflowstagesname' => '提单人现场确认',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H82',
      'isrole' => 'H82',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '379904',
      'workflowsid' => '379904',
      9 => '0',
      'timelimit' => '0',
      10 => 'MyCheck',
      'handleaction' => 'MyCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    5 => 
    array (
      0 => '379912',
      'workflowstagesid' => '379912',
      1 => '财务确认',
      'workflowstagesname' => '财务确认',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H90',
      'isrole' => 'H90',
      4 => '0',
      'iscost' => '0',
      5 => '5',
      'sequence' => '5',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '379904',
      'workflowsid' => '379904',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>