<?php

$workflows=array (
  0 => '393595',
  'workflowsid' => '393595',
  1 => '媒介部产品充值',
  'workflowsname' => '媒介部产品充值',
  2 => '1',
  'iscontract' => '1',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SalesOrder',
  'mountmodule' => 'SalesOrder',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '393621',
      'workflowstagesid' => '393621',
      1 => '开户',
      'workflowstagesname' => '开户',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H88',
      'isrole' => 'H88',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '393595',
      'workflowsid' => '393595',
      9 => '1',
      'timelimit' => '1',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '1',
      'iseditdata' => '1',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '393622',
      'workflowstagesid' => '393622',
      1 => '充值',
      'workflowstagesname' => '充值',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H109',
      'isrole' => 'H109',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '393595',
      'workflowsid' => '393595',
      9 => '2',
      'timelimit' => '2',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '1',
      'iseditdata' => '1',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '416884',
      'workflowstagesid' => '416884',
      1 => '财务审核',
      'workflowstagesname' => '财务审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H90 |##| H171',
      'isrole' => 'H90 |##| H171',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '393595',
      'workflowsid' => '393595',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'c_complete',
      'modulestatus' => 'c_complete',
      14 => '0',
      'isnextnode' => '0',
      15 => 'CONFIRM_TIME',
      'workflowstagesflag' => 'CONFIRM_TIME',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>