<?php

$workflows=array (
  0 => '400',
  'workflowsid' => '400',
  1 => '拜访单审核流程',
  'workflowsname' => '拜访单审核流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'VisitingOrder',
  'mountmodule' => 'VisitingOrder',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '470',
      'workflowstagesid' => '470',
      1 => '商务经理审核',
      'workflowstagesname' => '商务经理审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H80 |##| H81',
      'isrole' => 'H80 |##| H81',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '400',
      'workflowsid' => '400',
      9 => '8',
      'timelimit' => '8',
      10 => 'DepartmentalAudit',
      'handleaction' => 'DepartmentalAudit',
      11 => '0',
      'subworkflowsid' => '0',
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>