<?php

$workflows=array (
  0 => '414797',
  'workflowsid' => '414797',
  1 => '效果营销/上海珍岛DSP充值流程',
  'workflowsname' => '效果营销/上海珍岛DSP充值流程',
  2 => '1',
  'iscontract' => '1',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SalesOrder',
  'mountmodule' => 'SalesOrder',
  'stage' => 
  array (
    1 => 
    array (
      0 => '414800',
      'workflowstagesid' => '414800',
      1 => '项目/产品经理',
      'workflowstagesname' => '项目/产品经理',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H87 |##| H88',
      'isrole' => 'H87 |##| H88',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '414797',
      'workflowsid' => '414797',
      9 => '8',
      'timelimit' => '8',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '1',
      'iseditdata' => '1',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '414801',
      'workflowstagesid' => '414801',
      1 => '财务成本审核',
      'workflowstagesname' => '财务成本审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H90',
      'isrole' => 'H90',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '414797',
      'workflowsid' => '414797',
      9 => '8',
      'timelimit' => '8',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => 'CONFIRM_TIME',
      'workflowstagesflag' => 'CONFIRM_TIME',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '414802',
      'workflowstagesid' => '414802',
      1 => 'DSP充值',
      'workflowstagesname' => 'DSP充值',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102',
      'isrole' => 'H102',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '414797',
      'workflowsid' => '414797',
      9 => '8',
      'timelimit' => '8',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'c_complete',
      'modulestatus' => 'c_complete',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>