<?php

$workflows=array (
  0 => '434',
  'workflowsid' => '434',
  1 => '已匹配回款发票流程',
  'workflowsname' => '已匹配回款发票流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'Invoice',
  'mountmodule' => 'Invoice',
  'stage' => 
  array (
    1 => 
    array (
      0 => '379899',
      'workflowstagesid' => '379899',
      1 => '责任会计审核',
      'workflowstagesname' => '责任会计审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102 |##| H104 |##| H112 |##| H127 |##| H90',
      'isrole' => 'H102 |##| H104 |##| H112 |##| H127 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '434',
      'workflowsid' => '434',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '1392',
      'workflowstagesid' => '1392',
      1 => '开票员',
      'workflowstagesname' => '开票员',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102 |##| H104 |##| H121 |##| H90',
      'isrole' => 'H102 |##| H104 |##| H121 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '434',
      'workflowsid' => '434',
      9 => '8',
      'timelimit' => '8',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => '1',
      'iseditdata' => '1',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => 'edit_financial',
      'workflowstagesflag' => 'edit_financial',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '1393',
      'workflowstagesid' => '1393',
      1 => '发票领取',
      'workflowstagesname' => '发票领取',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102 |##| H104 |##| H112 |##| H121 |##| H90',
      'isrole' => 'H102 |##| H104 |##| H112 |##| H121 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '434',
      'workflowsid' => '434',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => 'receive_invoice',
      'workflowstagesflag' => 'receive_invoice',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>