<?php

$workflows=array (
  0 => '451476',
  'workflowsid' => '451476',
  1 => '网站上传工单内部流程',
  'workflowsname' => '网站上传工单内部流程',
  2 => '0',
  'iscontract' => '0',
  3 => '1',
  'iscontent' => '1',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SalesOrder',
  'mountmodule' => 'SalesOrder',
  'stage' => 
  array (
    1 => 
    array (
      0 => '451483',
      'workflowstagesid' => '451483',
      1 => '开发部主管',
      'workflowstagesname' => '开发部主管',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H87',
      'isrole' => 'H87',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '451476',
      'workflowsid' => '451476',
      9 => '0',
      'timelimit' => '0',
      10 => 'MyCheck',
      'handleaction' => 'MyCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '451484',
      'workflowstagesid' => '451484',
      1 => 'IDC服务器操作员',
      'workflowstagesname' => 'IDC服务器操作员',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H88',
      'isrole' => 'H88',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '451476',
      'workflowsid' => '451476',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '451486',
      'workflowstagesid' => '451486',
      1 => 'IDC主管签字',
      'workflowstagesname' => 'IDC主管签字',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H88',
      'isrole' => 'H88',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '451476',
      'workflowsid' => '451476',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'SERVICE_DESIGNATION',
      'workflowstagesflag' => 'SERVICE_DESIGNATION',
      'nostd' => 
      array (
      ),
    ),
    4 => 
    array (
      0 => '451487',
      'workflowstagesid' => '451487',
      1 => '客服部客服',
      'workflowstagesname' => '客服部客服',
      2 => '1',
      'isproductmanger' => '1',
      3 => 'H83 |##| H84 |##| H85',
      'isrole' => 'H83 |##| H84 |##| H85',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '451476',
      'workflowsid' => '451476',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>