<?php

$workflows=array (
  0 => '533',
  'workflowsid' => '533',
  1 => '合同产品审核子流程',
  'workflowsname' => '合同产品审核子流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SalesorderProductsrel',
  'mountmodule' => 'SalesorderProductsrel',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '534',
      'workflowstagesid' => '534',
      1 => '商务总监审核',
      'workflowstagesname' => '商务总监审核',
      2 => '1',
      'isproductmanger' => '1',
      3 => 'H32 |##| H54 |##| H61',
      'isrole' => 'H32 |##| H54 |##| H61',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '533',
      'workflowsid' => '533',
      9 => '8',
      'timelimit' => '8',
      10 => 'ChiefCheck',
      'handleaction' => 'ChiefCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '535',
      'workflowstagesid' => '535',
      1 => '产品负责人审核',
      'workflowstagesname' => '产品负责人审核',
      2 => '1',
      'isproductmanger' => '1',
      3 => 'H25',
      'isrole' => 'H25',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '533',
      'workflowsid' => '533',
      9 => '5',
      'timelimit' => '5',
      10 => 'ChiefCheck',
      'handleaction' => 'ChiefCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>