<?php

$workflows=array (
  0 => '537682',
  'workflowsid' => '537682',
  1 => '合同延期申请流程',
  'workflowsname' => '合同延期申请流程',
  2 => '1',
  'iscontract' => '1',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'ExtensionTrial',
  'mountmodule' => 'ExtensionTrial',
  'stage' => 
  array (
    1 => 
    array (
      0 => '537688',
      'workflowstagesid' => '537688',
      1 => '体系负责人/总监审核',
      'workflowstagesname' => '体系负责人/总监审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H115 |##| H116 |##| H78 |##| H79 |##| H83 |##| H86 |##| H94 |##| H96 |##| H97',
      'isrole' => 'H115 |##| H116 |##| H78 |##| H79 |##| H83 |##| H86 |##| H94 |##| H96 |##| H97',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '537682',
      'workflowsid' => '537682',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>