<?php

$workflows=array (
  0 => '549091',
  'workflowsid' => '549091',
  1 => '中小商务工单客服提单退款申请流程',
  'workflowsname' => '中小商务工单客服提单退款申请流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'OrderChargeback',
  'mountmodule' => 'OrderChargeback',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '549092',
      'workflowstagesid' => '549092',
      1 => '客服总监',
      'workflowstagesname' => '客服总监',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H83',
      'isrole' => 'H83',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '549091',
      'workflowsid' => '549091',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_actioning',
      'modulestatus' => 'b_actioning',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '549095',
      'workflowstagesid' => '549095',
      1 => '商务总监',
      'workflowstagesname' => '商务总监',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H79',
      'isrole' => 'H79',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '549091',
      'workflowsid' => '549091',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'BUSINESS_DIRECTOR',
      'workflowstagesflag' => 'BUSINESS_DIRECTOR',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '549098',
      'workflowstagesid' => '549098',
      1 => '销售体系部门负责人',
      'workflowstagesname' => '销售体系部门负责人',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H78',
      'isrole' => 'H78',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '549091',
      'workflowsid' => '549091',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    4 => 
    array (
      0 => '549099',
      'workflowstagesid' => '549099',
      1 => '项目/产品',
      'workflowstagesname' => '项目/产品',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H88',
      'isrole' => 'H88',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '549091',
      'workflowsid' => '549091',
      9 => '0',
      'timelimit' => '0',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'PRODUCT_SUPERIOR_CONFIRM',
      'workflowstagesflag' => 'PRODUCT_SUPERIOR_CONFIRM',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    5 => 
    array (
      0 => '549102',
      'workflowstagesid' => '549102',
      1 => '项目/产品审核人上级确认审核',
      'workflowstagesname' => '项目/产品审核人上级确认审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '5',
      'sequence' => '5',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '549091',
      'workflowsid' => '549091',
      9 => '0',
      'timelimit' => '0',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    6 => 
    array (
      0 => '549103',
      'workflowstagesid' => '549103',
      1 => '责任会计审核',
      'workflowstagesname' => '责任会计审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H127 |##| H90 |##| H171',
      'isrole' => 'H127 |##| H90 |##| H171',
      4 => '0',
      'iscost' => '0',
      5 => '6',
      'sequence' => '6',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '549091',
      'workflowsid' => '549091',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'COST_ACCOUNTING',
      'workflowstagesflag' => 'COST_ACCOUNTING',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    7 => 
    array (
      0 => '549106',
      'workflowstagesid' => '549106',
      1 => '发票管理员处理发票审核',
      'workflowstagesname' => '发票管理员处理发票审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102 |##| H90 |##| H171',
      'isrole' => 'H102 |##| H90 |##| H171',
      4 => '0',
      'iscost' => '0',
      5 => '7',
      'sequence' => '7',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '549091',
      'workflowsid' => '549091',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'INVOICE_CHECKED',
      'workflowstagesflag' => 'INVOICE_CHECKED',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    9 => 
    array (
      0 => '549109',
      'workflowstagesid' => '549109',
      1 => '财务刘莹审核',
      'workflowstagesname' => '财务刘莹审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H89',
      'isrole' => 'H89',
      4 => '0',
      'iscost' => '0',
      5 => '9',
      'sequence' => '9',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '549091',
      'workflowsid' => '549091',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    15 => 
    array (
      0 => '549110',
      'workflowstagesid' => '549110',
      1 => '出纳结算',
      'workflowstagesname' => '出纳结算',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H107',
      'isrole' => 'H107',
      4 => '0',
      'iscost' => '0',
      5 => '15',
      'sequence' => '15',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '549091',
      'workflowsid' => '549091',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>