<?php

$workflows=array (
  0 => '555702',
  'workflowsid' => '555702',
  1 => '非程序化充值申请流程',
  'workflowsname' => '非程序化充值申请流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'RefillApplication',
  'mountmodule' => 'RefillApplication',
  'stage' => 
  array (
    1 => 
    array (
      0 => '555703',
      'workflowstagesid' => '555703',
      1 => '主管审核',
      'workflowstagesname' => '主管审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H79',
      'isrole' => 'H79',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '555702',
      'workflowsid' => '555702',
      9 => '0',
      'timelimit' => '0',
      10 => 'UpCheck',
      'handleaction' => 'UpCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '555707',
      'workflowstagesid' => '555707',
      1 => '专员充值',
      'workflowstagesname' => '专员充值',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102 |##| H89',
      'isrole' => 'H102 |##| H89',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '555702',
      'workflowsid' => '555702',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>