<?php

$workflows=array (
  0 => '558406',
  'workflowsid' => '558406',
  1 => '程序化充值申请流程',
  'workflowsname' => '程序化充值申请流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'RefillApplication',
  'mountmodule' => 'RefillApplication',
  'stage' => 
  array (
    1 => 
    array (
      0 => '558408',
      'workflowstagesid' => '558408',
      1 => '商务总监审核',
      'workflowstagesname' => '商务总监审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H79',
      'isrole' => 'H79',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '558406',
      'workflowsid' => '558406',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'a_normal',
      'modulestatus' => 'a_normal',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '562635',
      'workflowstagesid' => '562635',
      1 => '体系负责人审核',
      'workflowstagesname' => '体系负责人审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H78',
      'isrole' => 'H78',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '558406',
      'workflowsid' => '558406',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '562636',
      'workflowstagesid' => '562636',
      1 => '专员充值',
      'workflowstagesname' => '专员充值',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102 |##| H89',
      'isrole' => 'H102 |##| H89',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '558406',
      'workflowsid' => '558406',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>