<?php

$workflows=array (
  0 => '573652',
  'workflowsid' => '573652',
  1 => '无垫款充值申请流程',
  'workflowsname' => '无垫款充值申请流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'RefillApplication',
  'mountmodule' => 'RefillApplication',
  'stage' => 
  array (
    1 => 
    array (
      0 => '573653',
      'workflowstagesid' => '573653',
      1 => '部门负责人审核',
      'workflowstagesname' => '部门负责人审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '573652',
      'workflowsid' => '573652',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '579817',
      'workflowstagesid' => '579817',
      1 => '充值平台审核',
      'workflowstagesname' => '充值平台审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '573652',
      'workflowsid' => '573652',
      9 => '0',
      'timelimit' => '0',
      10 => 'PlatformCheck',
      'handleaction' => 'PlatformCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '573654',
      'workflowstagesid' => '573654',
      1 => '财务充值',
      'workflowstagesname' => '财务充值',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102',
      'isrole' => 'H102',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '573652',
      'workflowsid' => '573652',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>