<?php

$workflows=array (
  0 => '596',
  'workflowsid' => '596',
  1 => '工作流测试1',
  'workflowsname' => '工作流测试1',
  2 => '1',
  'iscontract' => '1',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SalesOrder',
  'mountmodule' => 'SalesOrder',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    0 => 
    array (
      0 => '598',
      'workflowstagesid' => '598',
      1 => '2阶段',
      'workflowstagesname' => '2阶段',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '0',
      'sequence' => '0',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '596',
      'workflowsid' => '596',
      9 => '0',
      'timelimit' => '0',
      10 => 'ChiefCheck',
      'handleaction' => 'ChiefCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>