<?php

$workflows=array (
  0 => '599631',
  'workflowsid' => '599631',
  1 => '正常发票加签流程',
  'workflowsname' => '正常发票加签流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'Newinvoice',
  'mountmodule' => 'Newinvoice',
  'stage' => 
  array (
    1 => 
    array (
      0 => '599633',
      'workflowstagesid' => '599633',
      1 => '部门总监审核',
      'workflowstagesname' => '部门总监审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H115 |##| H78 |##| H79 |##| H83 |##| H86 |##| H87 |##| H88 |##| H94 |##| H95 |##| H96',
      'isrole' => 'H115 |##| H78 |##| H79 |##| H83 |##| H86 |##| H87 |##| H88 |##| H94 |##| H95 |##| H96',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '599631',
      'workflowsid' => '599631',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '599634',
      'workflowstagesid' => '599634',
      1 => '分管副总审核',
      'workflowstagesname' => '分管副总审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H115 |##| H123 |##| H78 |##| H86 |##| H94 |##| H96',
      'isrole' => 'H115 |##| H123 |##| H78 |##| H86 |##| H94 |##| H96',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '599631',
      'workflowsid' => '599631',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '599635',
      'workflowstagesid' => '599635',
      1 => '财务副经理',
      'workflowstagesname' => '财务副经理',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H89',
      'isrole' => 'H89',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '599631',
      'workflowsid' => '599631',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    4 => 
    array (
      0 => '599636',
      'workflowstagesid' => '599636',
      1 => '发票管理员开立发票',
      'workflowstagesname' => '发票管理员开立发票',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102 |##| H121 |##| H125 |##| H89 |##| H90',
      'isrole' => 'H102 |##| H121 |##| H125 |##| H89 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '599631',
      'workflowsid' => '599631',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'open_invoice',
      'workflowstagesflag' => 'open_invoice',
      'nostd' => 
      array (
      ),
    ),
    5 => 
    array (
      0 => '599638',
      'workflowstagesid' => '599638',
      1 => '发票领取',
      'workflowstagesname' => '发票领取',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102 |##| H121 |##| H89 |##| H90',
      'isrole' => 'H102 |##| H121 |##| H89 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '5',
      'sequence' => '5',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '599631',
      'workflowsid' => '599631',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'receive_invoice',
      'workflowstagesflag' => 'receive_invoice',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>