<?php

$workflows=array (
  0 => '599627',
  'workflowsid' => '599627',
  1 => '正常发票简易申请流程',
  'workflowsname' => '正常发票简易申请流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'Newinvoice',
  'mountmodule' => 'Newinvoice',
  'stage' => 
  array (
    1 => 
    array (
      0 => '599629',
      'workflowstagesid' => '599629',
      1 => '发票管理员开立发票',
      'workflowstagesname' => '发票管理员开立发票',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102 |##| H121 |##| H89 |##| H90',
      'isrole' => 'H102 |##| H121 |##| H89 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '599627',
      'workflowsid' => '599627',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'open_invoice',
      'workflowstagesflag' => 'open_invoice',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '599630',
      'workflowstagesid' => '599630',
      1 => '发票领取',
      'workflowstagesname' => '发票领取',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H102 |##| H121 |##| H89 |##| H90',
      'isrole' => 'H102 |##| H121 |##| H89 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '599627',
      'workflowsid' => '599627',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'receive_invoice',
      'workflowstagesflag' => 'receive_invoice',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>