<?php

$workflows=array (
  0 => '635',
  'workflowsid' => '635',
  1 => '工单产品审核子流程',
  'workflowsname' => '工单产品审核子流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SalesorderProductsrel',
  'mountmodule' => 'SalesorderProductsrel',
  'stage' => 
  array (
    1 => 
    array (
      0 => '1079',
      'workflowstagesid' => '1079',
      1 => '产品负责人写成本',
      'workflowstagesname' => '产品负责人写成本',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '635',
      'workflowsid' => '635',
      9 => '4',
      'timelimit' => '4',
      10 => 'ChiefCheck',
      'handleaction' => 'ChiefCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>