<?php

$workflows=array (
  0 => '639',
  'workflowsid' => '639',
  1 => '各部门报价流程',
  'workflowsname' => '各部门报价流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'Quotes',
  'mountmodule' => 'Quotes',
  'stage' => 
  array (
    1 => 
    array (
      0 => '1394',
      'workflowstagesid' => '1394',
      1 => '商务总监审核',
      'workflowstagesname' => '商务总监审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H79',
      'isrole' => 'H79',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '639',
      'workflowsid' => '639',
      9 => '0',
      'timelimit' => '0',
      10 => 'UpCheck',
      'handleaction' => 'UpCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '1395',
      'workflowstagesid' => '1395',
      1 => '部门报价',
      'workflowstagesname' => '部门报价',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H88',
      'isrole' => 'H88',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => '0',
      'manalert' => '0',
      7 => NULL,
      'auditalert' => NULL,
      8 => '639',
      'workflowsid' => '639',
      9 => '0',
      'timelimit' => '0',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '1865',
      'workflowstagesid' => '1865',
      1 => '项目/产品总监审核',
      'workflowstagesname' => '项目/产品总监审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H87 |##| H98 |##| H99',
      'isrole' => 'H87 |##| H98 |##| H99',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '639',
      'workflowsid' => '639',
      9 => '8',
      'timelimit' => '8',
      10 => 'ProductCheck',
      'handleaction' => 'ProductCheck',
      11 => '0',
      'subworkflowsid' => '0',
      12 => NULL,
      'iseditdata' => NULL,
      13 => NULL,
      'modulestatus' => NULL,
      14 => NULL,
      'isnextnode' => NULL,
      15 => NULL,
      'workflowstagesflag' => NULL,
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>