<?php

$workflows=array (
  0 => '792623',
  'workflowsid' => '792623',
  1 => '供应商审核流程',
  'workflowsname' => '供应商审核流程',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'Vendors',
  'mountmodule' => 'Vendors',
  'stage' => 
  array (
    1 => 
    array (
      0 => '796131',
      'workflowstagesid' => '796131',
      1 => '第一级审核',
      'workflowstagesname' => '第一级审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H115 |##| H79',
      'isrole' => 'H115 |##| H79',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '792623',
      'workflowsid' => '792623',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '796132',
      'workflowstagesid' => '796132',
      1 => '第二级审核',
      'workflowstagesname' => '第二级审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H115 |##| H78 |##| H94',
      'isrole' => 'H115 |##| H78 |##| H94',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '792623',
      'workflowsid' => '792623',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'audit_completed',
      'workflowstagesflag' => 'audit_completed',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>