<?php

$workflows=array (
  0 => '798888',
  'workflowsid' => '798888',
  1 => '合同补充协议审核流',
  'workflowsname' => '合同补充协议审核流',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'ContractsAgreement',
  'mountmodule' => 'ContractsAgreement',
  'stage' => 
  array (
    1 => 
    array (
      0 => '798889',
      'workflowstagesid' => '798889',
      1 => '上级一级审核',
      'workflowstagesname' => '上级一级审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '798888',
      'workflowsid' => '798888',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'AUDIT_VERIFICATION',
      'workflowstagesflag' => 'AUDIT_VERIFICATION',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '798890',
      'workflowstagesid' => '798890',
      1 => '上级二级审核',
      'workflowstagesname' => '上级二级审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '798888',
      'workflowsid' => '798888',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
    3 => 
    array (
      0 => '798891',
      'workflowstagesid' => '798891',
      1 => '财务主管审核',
      'workflowstagesname' => '财务主管审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '3',
      'sequence' => '3',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '798888',
      'workflowsid' => '798888',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'CREATE_CODE',
      'workflowstagesflag' => 'CREATE_CODE',
      'nostd' => 
      array (
      ),
    ),
    4 => 
    array (
      0 => '798892',
      'workflowstagesid' => '798892',
      1 => '合同打印',
      'workflowstagesname' => '合同打印',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H104 |##| H90',
      'isrole' => 'H104 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '4',
      'sequence' => '4',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '798888',
      'workflowsid' => '798888',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'b_check',
      'modulestatus' => 'b_check',
      14 => '0',
      'isnextnode' => '0',
      15 => 'DO_PRINT',
      'workflowstagesflag' => 'DO_PRINT',
      'nostd' => 
      array (
      ),
    ),
    5 => 
    array (
      0 => '798893',
      'workflowstagesid' => '798893',
      1 => '合同盖章',
      'workflowstagesname' => '合同盖章',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H104 |##| H90',
      'isrole' => 'H104 |##| H90',
      4 => '0',
      'iscost' => '0',
      5 => '5',
      'sequence' => '5',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '798888',
      'workflowsid' => '798888',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'c_stamp',
      'modulestatus' => 'c_stamp',
      14 => '0',
      'isnextnode' => '0',
      15 => '',
      'workflowstagesflag' => '',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>