<?php

$workflows=array (
  0 => '812777',
  'workflowsid' => '812777',
  1 => '采购合同作废工作流',
  'workflowsname' => '采购合同作废工作流',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'SupplierContracts',
  'mountmodule' => 'SupplierContracts',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '814171',
      'workflowstagesid' => '814171',
      1 => '出纳复核收款',
      'workflowstagesname' => '出纳复核收款',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H107 |##| H90 |##| H171',
      'isrole' => 'H107 |##| H90 |##| H171',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '812777',
      'workflowsid' => '812777',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'c_canceling',
      'modulestatus' => 'c_canceling',
      14 => '0',
      'isnextnode' => '0',
      15 => 'DO_RETURN_CANCEL',
      'workflowstagesflag' => 'DO_RETURN_CANCEL',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
    2 => 
    array (
      0 => '814172',
      'workflowstagesid' => '814172',
      1 => '合同管理员作废审核',
      'workflowstagesname' => '合同管理员作废审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => 'H104',
      'isrole' => 'H104',
      4 => '0',
      'iscost' => '0',
      5 => '2',
      'sequence' => '2',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '812777',
      'workflowsid' => '812777',
      9 => '0',
      'timelimit' => '0',
      10 => 'CommonCheck',
      'handleaction' => 'CommonCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'c_canceling',
      'modulestatus' => 'c_canceling',
      14 => '0',
      'isnextnode' => '0',
      15 => 'DO_CANCEL',
      'workflowstagesflag' => 'DO_CANCEL',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>