<?php

$workflows=array (
  0 => '828430',
  'workflowsid' => '828430',
  1 => '拜访单撤销申请',
  'workflowsname' => '拜访单撤销申请',
  2 => '0',
  'iscontract' => '0',
  3 => '0',
  'iscontent' => '0',
  4 => '0',
  'isattachment' => '0',
  5 => '0',
  'ischargeback' => '0',
  6 => 'VisitingOrder',
  'mountmodule' => 'VisitingOrder',
  7 => NULL,
  'dataupdate' => NULL,
  'stage' => 
  array (
    1 => 
    array (
      0 => '828433',
      'workflowstagesid' => '828433',
      1 => '提单人上撤销审核',
      'workflowstagesname' => '提单人上撤销审核',
      2 => '0',
      'isproductmanger' => '0',
      3 => '',
      'isrole' => '',
      4 => '0',
      'iscost' => '0',
      5 => '1',
      'sequence' => '1',
      6 => NULL,
      'manalert' => NULL,
      7 => NULL,
      'auditalert' => NULL,
      8 => '828430',
      'workflowsid' => '828430',
      9 => '0',
      'timelimit' => '0',
      10 => 'UpCheck',
      'handleaction' => 'UpCheck',
      11 => NULL,
      'subworkflowsid' => NULL,
      12 => '0',
      'iseditdata' => '0',
      13 => 'c_canceling',
      'modulestatus' => 'c_canceling',
      14 => '0',
      'isnextnode' => '0',
      15 => 'revoke_visitingorder',
      'workflowstagesflag' => 'revoke_visitingorder',
      16 => '0',
      'reviewer' => '0',
      'nostd' => 
      array (
      ),
    ),
  ),
);
?>