<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/

class AchievementallotStatistic_List_View extends Vtiger_KList_View {
    function preProcess(Vtiger_Request $request, $display = true)
    {
        $viewer = $this->getViewer($request);
        $recordModel=Vtiger_Record_Model::getCleanInstance('AchievementallotStatistic');
        $closingDate=Vtiger_Record_Model::getInstanceById(2434264,'ClosingDate');
        $date=$closingDate->get("date");
        $viewer->assign('date',$date);//业绩每月截止日期
        $viewer->assign('RECORD',$recordModel);
        parent::preProcess($request, $display); // TODO: Change the autogenerated stub
    }

    function process (Vtiger_Request $request, $display=true)
    {
        //parent::process();
        $strPublic = $request->get('public');
        if($strPublic == 'exportdata') {//自定义导出
            global $site_URL,$current_user;
            header('location:'.$site_URL.'temp/achievementallotstatistic'.$current_user->id.'.xlsx');
            exit;
        }
        if($strPublic=='departset'){
            $recordModel = Vtiger_Record_Model::getCleanInstance('AchievementallotStatistic');
            if(!$recordModel->personalAuthority('AchievementallotStatistic','departset')){
                exit;
            }
            include 'crmcache/departmentanduserinfo.php';
            $viewer = $this->getViewer($request);
            $viewer->assign('USERDEPARTMENT',getDepartment());
            $viewer->assign('USER',$recordModel->getUserIDName());
            $viewer->assign('DEPARTMENT',getDepartment());
            $viewer->assign('RECOEDS',$recordModel->getDepartmentData());
            $viewer->assign('PARTMENTS',$cachedepartment);
            $viewer->view('departset.tpl', 'AchievementallotStatistic');
            return ;
        }
        $viewer = $this->getViewer($request);
        $recordModel=Vtiger_Record_Model::getCleanInstance('AchievementSummary');
        $viewer->assign('RECORD',$recordModel);
        parent::process($request);
    }
}