<?php

class Knowledge extends baseapp{
	private $pagecount = 10;
	public function index(){
		
		$this->smarty->display('VisitingOrder/index.html');
	}
	#查看新闻通知;
	public function notice(){
        $this->smarty->assign('title','新闻公告');
		$pagenum 	= isset($_REQUEST['pagenum'])?$_REQUEST['pagenum']:1;

		$params  = array(
			'fieldname'=>array('pagenum' 	=> $pagenum,
						   	   'pagecount'  => $this->pagecount,
						   	   'userid'		=> $this->userid,
                                'filter'		=> 'NewList'
						   )
		);
		$list = $this->call('get_NewList', $params);
      //  var_dump($list);
		$this->smarty->assign('sum',$list[0]);
		$sumpage = intval(($list[0]+1)/$this->pagecount);
		$this->smarty->assign('sumpage',$sumpage);

		$this->smarty->assign('list',$list[1]);
        $this->smarty->display('Knowledge/notice.html');
	}
	#待审核拜访
    public function run($action = 'index')
    {
        parent::run($action); // TODO: Change the autogenerated stub
    }
}

